package com.mp.entity;
// Generated 2017/10/8 �U�� 10:36:56 by Hibernate Tools 5.2.5.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemberInfo generated by hbm2java
 */
@Entity
@Table(name = "basket", catalog = "wendy")
public class Basket extends BaseEntity {
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)  
	private Integer basketNo;
	private String basketProduct;
	private String basketAmount;
	
	public Integer getBasketNo() {
		return basketNo;
	}
	public void setBasketNo(Integer basketNo) {
		this.basketNo = basketNo;
	}
	public String getBasketProduct() {
		return basketProduct;
	}
	public void setBasketProduct(String basketProduct) {
		this.basketProduct = basketProduct;
	}
	public String getBasketAmount() {
		return basketAmount;
	}
	public void setBasketAmount(String basketAmount) {
		this.basketAmount = basketAmount;
	}
	
	


}
