package com.mp.entity;
// Generated 2017/10/8 �U�� 10:36:56 by Hibernate Tools 5.2.5.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemberInfo generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "wendy")
public class Brand extends BaseEntity {
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)  
	private Integer brandNo;
	private String brand;
	public Integer getBrandNo() {
		return brandNo;
	}
	public void setBrandNo(Integer brandNo) {
		this.brandNo = brandNo;
	}
	public String getBrand() {
		return brand;
	}
	public void setBrand(String brand) {
		this.brand = brand;
	}
	
	


}
