package com.mp.entity;
// Generated 2017/10/8 �U�� 10:36:56 by Hibernate Tools 5.2.5.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemberInfo generated by hbm2java
 */
@Entity
@Table(name = "color", catalog = "wendy")
public class Color extends BaseEntity {
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)  
	private Integer colorNo;
	private String color;
	
	//右鍵==>source==>genetater getter and setter 可自行創建下方方法
	public Integer getColorNo() {
		return colorNo;
	}
	public void setColorNo(Integer colorNo) {
		this.colorNo = colorNo;
	}
	public String getColor() {
		return color;
	}
	public void setColor(String color) {
		this.color = color;
	}
	
	


}
