package com.mp.entity;
// Generated 2017/10/8 �U�� 10:36:56 by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemberInfo generated by hbm2java
 */
@Entity
@Table(name = "member_info", catalog = "test")
public class MemberInfo extends BaseEntity {

	private String memberNo;
	private String account;
	private String password;
	private String authority;
	private String status;
	private Integer errorTime;
	private String lastModified;

	public MemberInfo() {
	}

	public MemberInfo(String memberNo, String account) {
		this.memberNo = memberNo;
		this.account = account;
	}

	public MemberInfo(String memberNo, String account, String password, String authority, String status,
			Integer errorTime, String lastModified) {
		this.memberNo = memberNo;
		this.account = account;
		this.password = password;
		this.authority = authority;
		this.status = status;
		this.errorTime = errorTime;
		this.lastModified = lastModified;
	}

	@Id

	@Column(name = "member_no", unique = true, nullable = false, length = 100)
	public String getMemberNo() {
		return this.memberNo;
	}

	public void setMemberNo(String memberNo) {
		this.memberNo = memberNo;
	}

	@Column(name = "account", nullable = false, length = 70)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "authority", length = 1)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "error_time")
	public Integer getErrorTime() {
		return this.errorTime;
	}

	public void setErrorTime(Integer errorTime) {
		this.errorTime = errorTime;
	}

	@Column(name = "last_modified", length = 14)
	public String getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(String lastModified) {
		this.lastModified = lastModified;
	}

}
